-- AlterTable
ALTER TABLE "public"."pago" ADD COLUMN     "ciudad" VARCHAR(100),
ADD COLUMN     "direccion_actual" VARCHAR(255),
ADD COLUMN     "encargado" VARCHAR(100),
ADD COLUMN     "estado" VARCHAR(50),
ADD COLUMN     "estado_civil" VARCHAR(50),
ADD COLUMN     "fecha_nacimiento" TIMESTAMP(3),
ADD COLUMN     "forma_contacto" VARCHAR(50),
ADD COLUMN     "migratorio_dependientes" VARCHAR(255),
ADD COLUMN     "migratorio_estatus_actual" VARCHAR(50),
ADD COLUMN     "migratorio_fecha_entrada_eeuu" TIMESTAMP(3),
ADD COLUMN     "migratorio_fecha_vencimiento_estadia" TIMESTAMP(3),
ADD COLUMN     "migratorio_numero_caso" VARCHAR(50),
ADD COLUMN     "migratorio_tipo_proceso" VARCHAR(100),
ADD COLUMN     "migratorio_ubicacion_actual" VARCHAR(100),
ADD COLUMN     "migratorio_via_entrada_eeuu" VARCHAR(50),
ADD COLUMN     "nivel_estudios" VARCHAR(100),
ADD COLUMN     "notas_cliente" VARCHAR(1000),
ADD COLUMN     "numero_documento" VARCHAR(50),
ADD COLUMN     "ocupacion_actual" VARCHAR(100),
ADD COLUMN     "pais_nacimiento" VARCHAR(100),
ADD COLUMN     "pais_origen" VARCHAR(100),
ADD COLUMN     "tipo_documento" VARCHAR(50),
ADD COLUMN     "tipo_proceso" VARCHAR(100),
ADD COLUMN     "zipcode" VARCHAR(20);
